metadata.format.version = "1.1"

[versions]

velocity = "3.4.0-SNAPSHOT"
paper = "1.21.8-R0.1-SNAPSHOT"
sponge = "14.0.0"

blossom = "2.1.0"
shadow = "9.0.2"
runtask = "2.3.1"

miniplaceholders = "3.0.0-SNAPSHOT"
adventure = "4.24.0"
adventurefabric = "6.6.0"

fabric-loader = "0.17.2"
fabric-api = "0.131.0+1.21.8"
minecraft = "1.21.8"

[libraries]

minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
papermc = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
sponge = { module = "org.spongepowered:spongeapi", version.ref = "sponge" }

fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

miniplaceholders = { group = "io.github.miniplaceholders", name = "miniplaceholders-api", version.ref = "miniplaceholders" }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure" }
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-platform-fabric = { group = "net.kyori", name = "adventure-platform-fabric", version.ref = "adventurefabric" }

caffeine = "com.github.ben-manes.caffeine:caffeine:3.2.2"

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
runpaper = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version = "1.3" }